import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <div className="container header-container align-content-between">
            {/* <div className="row header-row-1">
              <div className="col-auto header-col"><a href="/"><Image src="/images/Logo.svg" width={0} height={0} sizes="100vw" style={{ width: '50px', height: 'auto' }}></Image></a></div>
              <div className="col-auto header-col"><a href="/">Краснодар</a></div>
              <div className="col-auto header-col"><a href="/">8 (600) 400-2-300</a></div>

            </div>
            <div className="line-inbetween"></div> */}
            <div className="row header-row-1" style={{ height: '100%' }}>
              <div className="col-auto header-col"><a href="/"><Image src="/images/Logo.svg" alt="logo" width={0} height={0} sizes="100vw" style={{ width: 'auto', height: '50px' }}/></a></div>
              <div className="col-auto header-col"><a href="/">Главная</a></div>
              <div className="col-auto header-col"><a href="/doctors">Специалисты</a></div>
              <div className="col-auto header-col"><a href="/services">Услуги</a></div>
              <div className="col-auto header-col"><a href="/about">О нас</a></div>


            </div>
          </div>
        </header>
        <main className="container">
          {children}
        </main>
      </body>
    </html>
  );
}
